import 'package:flutter/material.dart';

class APIUrls {
  static const String mosambeeusername = "9814414463";
  static const String mosambeepassword = "1321";

  static const String login =
      "https://phylopos.in/Ameerii/erp/Apis/login/?username=";
  static const String dasboarddata =
      "https://phylopos.in/Ameerii/erp/Apis/dasboarddata?id=";
  static const String category_list =
      "https://phylopos.in/Ameerii/erp/Apis/category_list?id=";
  static const String allproduct_list =
      "https://phylopos.in/Ameerii/erp/Apis/allproduct_list?id=";
  static const String product_list =
      "https://phylopos.in/Ameerii/erp/Apis/product_list?id=";
  static const String orderhistorysave =
      "https://phylopos.in/Ameerii/erp/Apis/orderhistorysave?id=";
  static const String orderpaymentsave =
      "https://phylopos.in/Ameerii/erp/Apis/orderpaymentsave?id=";
  static const String orderhistorysave_table =
      "https://phylopos.in/Ameerii/erp/Apis/orderhistorysave_table?id=";
  static const String reprint_data =
      "https://phylopos.in/Ameerii/erp/Apis/reprint_data?id=";
  static const String data_report =
      "https://phylopos.in/Ameerii/erp/Apis/data_report?id=";
  static const String dsr_report_print =
      "https://phylopos.in/Ameerii/erp/Apis/dsr_report_print?id=";
  static const String wallet_report_print =
      "https://phylopos.in/Ameerii/erp/Apis/wallet_report_print?id=";
  static const String itemsale_report_print =
      "https://phylopos.in/Ameerii/erp/Apis/item_sale_report?id=";
  static const String table_list =
      "https://phylopos.in/Ameerii/erp/Apis/table_list?id=";
  static const String swap_table =
      "https://phylopos.in/Ameerii/erp/Apis/swap_table?id=";
  static const String orderpaymentsave_table =
      "https://phylopos.in/Ameerii/erp/Apis/orderpaymentsave_table?id=";
  static const String quantity_increase =
      "https://phylopos.in/Ameerii/erp/Apis/quantity_increase?id=";
  static const String quantity_decrease =
      "https://phylopos.in/Ameerii/erp/Apis/quantity_decrease?id=";
  static const String remove_item =
      "https://phylopos.in/Ameerii/erp/Apis/remove_item?id=";
  static const String bill_table =
      "https://phylopos.in/Ameerii/erp/Apis/bill_table?id=";
  static const String table_unbill =
      "https://phylopos.in/Ameerii/erp/Apis/table_unbill?id=";
  static const String table_clear =
      "https://phylopos.in/Ameerii/erp/Apis/table_clear?id=";
  static const String table_billupdate_servicecharge =
      "https://phylopos.in/Ameerii/erp/Apis/table_billupdate_servicecharge?id=";
  static const String table_billupdate_discount =
      "https://phylopos.in/Ameerii/erp/Apis/table_billupdate_discount?id=";
  static const String table_billupdate_coupon =
      "https://phylopos.in/Ameerii/erp/Apis/table_billupdate_coupon?id=";
  static const String table_bill_coupon_removed =
      "https://phylopos.in/Ameerii/erp/Apis/table_bill_coupon_removed?id=";
  static const String card_validity_options =
      "https://phylopos.in/Ameerii/erp/Apis/card_validity_options?id=";
  static const String card_payment_options =
      "https://phylopos.in/Ameerii/erp/Apis/card_payment_options?id=";
  static const String cardstatuscheck =
      "https://phylopos.in/Ameerii/erp/Apis/cardstatuscheck?id=";
  static const String cardaddbalance =
      "https://phylopos.in/Ameerii/erp/Apis/cardaddbalance?id=";
  static const String cardcreate =
      "https://phylopos.in/Ameerii/erp/Apis/cardcreate?id=";
  static const String cardtransfer =
      "https://phylopos.in/Ameerii/erp/Apis/cardtransfer?id=";
  static const String card_history =
      "https://phylopos.in/Ameerii/erp/Apis/card_history?id=";
  static const String reprint_kot_group =
      "https://phylopos.in/Ameerii/erp/Apis/reprint_kot?id=";
  static const String quick_billupdate_discount =
      "https://phylopos.in/Ameerii/erp/Apis/quick_billupdate_discount?id=";
  static const String quick_billupdate_coupon =
      "https://phylopos.in/Ameerii/erp/Apis/quick_billupdate_coupon?id=";
  static const String quick_bill_coupon_removed =
      "https://phylopos.in/Ameerii/erp/Apis/quick_bill_coupon_removed?id=";
  static const String payment_storecard =
      "https://phylopos.in/Ameerii/erp/Apis/payment_storecard?id=";
  static const String payment_storecard_table =
      "https://phylopos.in/Ameerii/erp/Apis/payment_storecard_table?id=";
}
